"""Obsidian vault sync module.

Writes pipeline output to the Obsidian vault as markdown files.
All writes are best-effort - failures here never break the pipeline.
"""

import logging
import os
import re
from datetime import datetime

from config import CONTENT_PILLARS, OBSIDIAN_VAULT_PATH

logger = logging.getLogger(__name__)

LINKEDIN_PATH = os.path.join(OBSIDIAN_VAULT_PATH, "LinkedIn")
POST_LOG_PATH = os.path.join(LINKEDIN_PATH, "Post Log")
IDEAS_PATH = os.path.join(OBSIDIAN_VAULT_PATH, "Ideas")


def _ensure_dirs():
    """Create vault directories if they don't exist."""
    for path in [POST_LOG_PATH, IDEAS_PATH]:
        os.makedirs(path, exist_ok=True)


def _week_id(date):
    """Return ISO week string like '2026-W10'."""
    return f"{date.isocalendar()[0]}-W{date.isocalendar()[1]:02d}"


def _read_file(path):
    """Read file contents or return None if missing."""
    try:
        with open(path, encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return None


def _write_file(path, content):
    """Write content to file, creating parent dirs as needed."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    logger.info(f"Wrote vault file: {path}")


def _new_post_log(week_id):
    """Create a fresh weekly post log from template."""
    return f"""# Post Log - {week_id}

## Drafts Generated

| Date | Format | Category | Persona | Source | Hook Score | Composite | Posted? | Impressions | Comments | Likes |
|------|--------|----------|---------|--------|------------|-----------|---------|-------------|----------|-------|

## Weekly Totals

- **Posts published:** /5
- **Total impressions:**
- **Total comments:**
- **Best performer:**
- **Worst performer:**

## Notes



---

*Auto-generated by `obsidian_output.py`*
"""


def sync_post_log(drafts, date):
    """Append today's drafts to the weekly post log note.

    Creates the file from template if it doesn't exist.
    """
    _ensure_dirs()
    week_id = _week_id(date)
    log_path = os.path.join(POST_LOG_PATH, f"{week_id}.md")
    date_str = date.strftime("%Y-%m-%d")

    existing = _read_file(log_path)
    if existing is None:
        existing = _new_post_log(week_id)

    rows = []
    for draft in drafts:
        article = draft.get("article", {})
        fmt = draft.get("content_format", "text")
        category = article.get("category", "")
        persona = draft.get("persona", "")
        source = article.get("source", "")
        hook_score = draft.get("hook_score", "")
        composite = draft.get("composite_score", "")
        rows.append(
            f"| {date_str} | {fmt} | {category} | {persona} | {source} "
            f"| {hook_score} | {composite} | [ ] | | | |"
        )

    new_rows = "\n".join(rows)

    # Insert rows before the Weekly Totals section
    if "## Weekly Totals" in existing:
        existing = existing.replace(
            "## Weekly Totals",
            f"{new_rows}\n\n## Weekly Totals",
        )
    else:
        # Fallback: append to end of table
        existing = existing.rstrip() + "\n" + new_rows + "\n"

    _write_file(log_path, existing)
    logger.info(f"Synced {len(drafts)} drafts to post log {week_id}")


def update_content_calendar(drafts, date):
    """Update today's row in Content Calendar.md."""
    calendar_path = os.path.join(LINKEDIN_PATH, "Content Calendar.md")
    existing = _read_file(calendar_path)
    if existing is None:
        logger.warning("Content Calendar.md not found, skipping calendar update")
        return

    day_abbr = date.strftime("%a")  # Mon, Tue, etc.
    day_num = date.strftime("%-d")  # 3, 4, etc.

    for draft in drafts:
        article = draft.get("article", {})
        fmt = draft.get("content_format", "text")
        angle = article.get("one_line_summary", article.get("title", ""))
        # Truncate angle to keep table readable
        if len(angle) > 60:
            angle = angle[:57] + "..."

        # Try to find and update today's row in the table
        # Match pattern like "| Mon 3 |" or "| Tue 4 |"
        pattern = rf"(\| {day_abbr} {day_num} \|)[^\n]*"
        week_id = _week_id(date)
        replacement = (
            f"| {day_abbr} {day_num} | {fmt} | {angle} | Drafted | "
            f"| [[LinkedIn/Post Log/{week_id}\\|{week_id}]] |"
        )

        if re.search(pattern, existing):
            existing = re.sub(pattern, replacement, existing, count=1)
        else:
            logger.debug(f"No calendar row found for {day_abbr} {day_num}")

    _write_file(calendar_path, existing)
    logger.info("Updated Content Calendar")


def write_story_scaffold(draft):
    """When a story_prompt format is generated, create a scaffold note in Ideas/."""
    _ensure_dirs()
    article = draft.get("article", {})
    scaffold = draft.get("story_scaffold", "")
    if not scaffold:
        return

    title = article.get("title", "Story Scaffold")
    # Clean title for filename
    safe_title = re.sub(r'[^\w\s-]', '', title)[:60].strip()
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"Story Scaffold - {date_str} - {safe_title}.md"
    filepath = os.path.join(IDEAS_PATH, filename)

    # Find matching Story Bank entries by checking pillar keywords
    category = article.get("category", "")
    pillar_links = []
    pillar_map = {
        "eCommerce": "Fix the Basics First",
        "Email Marketing": "Fix the Basics First",
        "AI": "The AI Realist",
        "AI in eCommerce": "The AI Realist",
        "AI in Sales": "The AI Realist",
        "Sales": "Sales Without the Script",
        "Behavioural Science": "The Digital Outsider",
    }
    matched_pillar = pillar_map.get(category, "")
    if matched_pillar:
        pillar_links.append(
            f"- Check [[LinkedIn/Story Bank/Story Bank Index|Story Bank]] "
            f"under **{matched_pillar}**"
        )

    content = f"""# Story Scaffold - {date_str}

**Source article:** {title} ({article.get('source', 'Unknown')})
**Category:** {category}
**Persona:** {draft.get('persona', '')}

---

## Writing Prompt

{scaffold}

## Suggested Story Bank Connections

{chr(10).join(pillar_links) if pillar_links else '- Review [[LinkedIn/Story Bank/Story Bank Index|Story Bank]] for matching experiences'}

## Hooks to Try

1.
2.
3.

## Your Story

> Write your personal take here. What experience does this connect to?



---

*Auto-generated by `obsidian_output.py` on {date_str}*
"""

    _write_file(filepath, content)
    logger.info(f"Created story scaffold: {filename}")


def update_dashboard(history):
    """Update the numbers and format performance sections in LinkedIn Dashboard.md.

    Called by --weekly-summary and --log-metrics.
    Leaves qualitative fields (why it worked/flopped, actions) for Russell.
    """
    from collections import Counter
    from calendar_tracker import get_recent_posts

    dashboard_path = os.path.join(LINKEDIN_PATH, "LinkedIn Dashboard.md")
    existing = _read_file(dashboard_path)
    if existing is None:
        logger.warning("LinkedIn Dashboard.md not found, skipping dashboard update")
        return

    recent = get_recent_posts(history, days=7)
    posts_with_metrics = [p for p in recent if "metrics" in p]

    # Build format performance table
    format_data = {}
    for p in posts_with_metrics:
        fmt = p.get("content_format", "text")
        imp = p["metrics"].get("impressions", 0)
        if fmt not in format_data:
            format_data[fmt] = []
        format_data[fmt].append(imp)

    format_rows = []
    for fmt in ["text", "carousel", "poll", "opinion", "story_prompt"]:
        if fmt in format_data:
            imps = format_data[fmt]
            avg = sum(imps) // len(imps)
            format_rows.append(f"| {fmt} | {len(imps)} | {avg:,} | |")
        else:
            format_rows.append(f"| {fmt} | | | |")

    format_table = "\n".join(format_rows)

    # Replace format performance section
    format_pattern = (
        r"(## Format Performance\n\n"
        r"\| Format \| Posts \| Avg Impressions \| Notes \|\n"
        r"\|--------|-------|-----------------|-------\|\n)"
        r"(.*?)(?=\n\n##)"
    )
    format_replacement = rf"\g<1>{format_table}"
    existing = re.sub(format_pattern, format_replacement, existing, flags=re.DOTALL)

    # Update pillar balance
    pillar_counts = Counter()
    category_to_pillar = {
        "eCommerce": "Fix the Basics First",
        "Email Marketing": "Fix the Basics First",
        "AI": "The AI Realist",
        "AI in eCommerce": "The AI Realist",
        "AI in Sales": "The AI Realist",
        "Sales": "Sales Without the Script",
        "Behavioural Science": "The Digital Outsider",
    }
    for p in recent:
        pillar = category_to_pillar.get(p.get("category", ""), "Unknown")
        pillar_counts[pillar] += 1

    pillar_rows = []
    for pillar in CONTENT_PILLARS:
        count = pillar_counts.get(pillar, 0)
        pillar_rows.append(f"| {pillar} | {count} | 1-2 |")

    pillar_table = "\n".join(pillar_rows)
    pillar_pattern = (
        r"(## Pillar Balance\n\n"
        r"\| Pillar \| Posts This Week \| Target \|\n"
        r"\|--------|----------------\|--------\|\n)"
        r"(.*?)(?=\n\n##)"
    )
    pillar_replacement = rf"\g<1>{pillar_table}"
    existing = re.sub(pillar_pattern, pillar_replacement, existing, flags=re.DOTALL)

    # Update week header and follower info
    now = datetime.now()
    week_id = _week_id(now)
    mon = now.date()
    # Find Monday of this week
    from datetime import timedelta
    days_since_monday = mon.weekday()
    monday = mon - timedelta(days=days_since_monday)
    friday = monday + timedelta(days=4)
    week_range = f"{monday.day}-{friday.day} {monday.strftime('%B')}"

    existing = re.sub(
        r"\*\*Week:\*\* .*",
        f"**Week:** {week_id} ({week_range})",
        existing,
    )

    _write_file(dashboard_path, existing)
    logger.info("Updated LinkedIn Dashboard")


def sync_all(history):
    """Backfill post logs from entire post_history.json.

    Called by --sync-obsidian.
    """
    _ensure_dirs()
    posts = history.get("posts", [])
    if not posts:
        logger.info("No posts in history to sync")
        return

    # Group posts by ISO week
    weeks = {}
    for post in posts:
        date_str = post.get("date", "")
        if not date_str:
            continue
        try:
            date = datetime.fromisoformat(date_str)
        except ValueError:
            continue
        week_id = _week_id(date)
        if week_id not in weeks:
            weeks[week_id] = []
        weeks[week_id].append((date, post))

    for week_id, entries in sorted(weeks.items()):
        log_path = os.path.join(POST_LOG_PATH, f"{week_id}.md")
        content = _new_post_log(week_id)

        rows = []
        for date, post in sorted(entries, key=lambda x: x[0]):
            date_str = date.strftime("%Y-%m-%d")
            fmt = post.get("content_format", "text")
            category = post.get("category", "")
            persona = post.get("persona", "")
            source = post.get("source", "")

            # Pull metrics if available
            metrics = post.get("metrics", {})
            impressions = metrics.get("impressions", "")
            comments = metrics.get("comments", "")
            likes = metrics.get("likes", "")

            rows.append(
                f"| {date_str} | {fmt} | {category} | {persona} | {source} "
                f"| | | [x] | {impressions} | {comments} | {likes} |"
            )

        new_rows = "\n".join(rows)
        content = content.replace(
            "## Weekly Totals",
            f"{new_rows}\n\n## Weekly Totals",
        )
        _write_file(log_path, content)

    # Update Post Log Index with all weeks
    index_path = os.path.join(POST_LOG_PATH, "Post Log Index.md")
    existing_index = _read_file(index_path)
    if existing_index:
        week_table_rows = []
        for week_id in sorted(weeks.keys(), reverse=True):
            count = len(weeks[week_id])
            week_table_rows.append(
                f"| [[LinkedIn/Post Log/{week_id}|{week_id}]] | {count} | |"
            )
        new_table = "\n".join(week_table_rows)

        # Replace the table rows after the header
        existing_index = re.sub(
            r"(## Weekly Logs\n\n\| Week \| Posts \| Notes \|\n\|------\|-------\|-------\|\n).*?(?=\n\n##)",
            rf"\g<1>{new_table}",
            existing_index,
            flags=re.DOTALL,
        )
        _write_file(index_path, existing_index)

    logger.info(f"Backfilled {len(weeks)} weekly post logs from history")
